backend:
  name: github
  repo: geekypepito/schedulerama-site
  branch: main
  site_domain: www.schedulerama.com
  base_url: https://www.schedulerama.com
  auth_endpoint: /cms-auth/auth

media_folder: public/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    files:
      - label: Home
        name: home
        file: src/pages/index.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: About
        name: about
        file: src/pages/about.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Pricing
        name: pricing
        file: src/pages/pricing.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Contact
        name: contact
        file: src/pages/contact.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true

  - name: product
    label: Product Pages
    files:
      - label: Facility Operations
        name: facility_operations
        file: src/pages/product/facility-operations.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Game Finder
        name: game_finder
        file: src/pages/product/game-finder.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Group Scheduler
        name: group_scheduler
        file: src/pages/product/group-scheduler.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Operational Workflows
        name: operational_workflows
        file: src/pages/product/operational-workflows.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Organization Data
        name: organization_data
        file: src/pages/product/organization-data.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Realtime Messaging
        name: realtime_messaging
        file: src/pages/product/realtime-messaging.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Reports and Import
        name: reports_import
        file: src/pages/product/reports-import.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Requests Inbox
        name: requests_inbox
        file: src/pages/product/requests-inbox.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Schedule Management
        name: schedule_management
        file: src/pages/product/schedule-management.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true

  - name: solutions
    label: Solutions Pages
    files:
      - label: Athletic Directors
        name: athletic_directors
        file: src/pages/solutions/athletic-directors.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Coaches
        name: coaches
        file: src/pages/solutions/coaches.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Game Officials
        name: game_officials
        file: src/pages/solutions/game-officials.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: League Admins
        name: league_admins
        file: src/pages/solutions/league-admins.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Maintenance
        name: maintenance
        file: src/pages/solutions/maintenance.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Super Admins
        name: super_admins
        file: src/pages/solutions/super-admins.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Transportation
        name: transportation
        file: src/pages/solutions/transportation.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true

  - name: resources
    label: Resources Pages
    files:
      - label: FAQ
        name: faq
        file: src/pages/resources/faq.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Feature Matrix
        name: feature_matrix
        file: src/pages/resources/feature-matrix.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: Release Notes
        name: release_notes
        file: src/pages/resources/release-notes.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
      - label: User Guide
        name: user_guide
        file: src/pages/resources/user-guide.astro
        format: astro-raw
        editor:
          preview: false
        fields:
          - label: Page Source
            name: body
            widget: code
            default_language: html
            output_code_only: true
